# CC = clang++ -std=c++11
CC = g++-4.8 -std=c++11

all: TestTrailMaking TestClaves

TestTrailMaking: TestTrailMaking.cpp
			${CC} TestTrailMaking.cpp -o TestTrailMaking 

TestClaves: TestClaves.cc 
			${CC} TestClaves.cc -o  TestClaves 



